### ISSUE TITLE
Disabling on certain websites 

### ISSUE THREAD

**Issue by ulysses4ever** [vim-vix-remix/vim-vix-remix#7]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Some websites use Vim keys for navigation, which may be handy. One example is GMail, which has nice navigation using j-k-l-h. After installing the extension, I can't use that. I wish there was a way to disable the extension on certain websites so that I could employ their support for Vim keys.

**Comment by jiriks74** [comment]
There is a blacklist in the extension settings.

**Comment by ulysses4ever** [comment]
Ouch, that is embarrassing! I can see it now. Switching to JSON format wasn't a great idea: it was too easy to miss important stuff...

Thank you!
